version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./backend/.env
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local